### CREATE five documents.
POST http://localhost:3000/purchases HTTP/1.1
content-type: application/json

{
    "productName": "Rubbermaid Freshworks Produce Saver",
    "price": 29.98,
    "purchaseDate": "2024-02-26"
}


### CREATE 2
POST http://localhost:3000/purchases HTTP/1.1
content-type: application/json

{
    "productName": "How the World Really Works: A Scientist's Guide to Our Past, Present, and Future",
    "price": 14.85,
    "purchaseDate": "2024-02-25"
}

### CREATE 3
POST http://localhost:3000/purchases HTTP/1.1
content-type: application/json

{
    "productName": "CloudBliss Memory Foam Pillow",
    "price": 22.49,
    "purchaseDate": "2024-02-24"
}

### CREATE 4
POST http://localhost:3000/purchases HTTP/1.1
content-type: application/json

{
    "productName": "Cuisinart Air Fryer + Convection Toaster Oven",
    "price": 214,
    "purchaseDate": "2024-02-12"
}

### CREATE 5
POST http://localhost:3000/purchases HTTP/1.1
content-type: application/json

{
    "productName": "Boston Advance Contact Lens Solution",
    "price": 21.70,
    "purchaseDate": "2024-02-03"
}


### RETRIEVE all documents.
GET http://localhost:3000/purchases HTTP/1.1



### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/purchases/65e55afe4bec0a2a8cc9c383 HTTP/1.1


### UPDATE one document's price, by ID.
### Replace the ID in the following request with one that exists
### and update the price:
PUT http://localhost:3000/purchases/65e55afe4bec0a2a8cc9c383 HTTP/1.1
content-type: application/json

{
    "productName": "Rubbermaid Freshworks Produce Saver",
    "price": 30.98,
    "purchaseDate": "2024-02-26"
}

### DELETE by ID (responds with nothing if successful):
DELETE http://localhost:3000/purchases/65e55afe4bec0a2a8cc9c383 HTTP/1.1



### RETRIEVE all documents (responds with 4 or the original 5):
GET http://localhost:3000/purchases HTTP/1.1

